### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by lonix1** [scottkuhl/FluentBootstrap#2]
Have you found a way to use this with blazor?

**Comment by scottkuhl** [comment]
If you are using the default templates from Microsoft they are based on Bootstrap, but they are not setup for Sass.  And the newer templates based on .NET 6 are based on Bootstrap 5, not 4 like these were setup for.  But it should not be too much work to get it working.

1. Copy the bootstrap.scss, _dark.scss, _light.scss into a folder in the wwwroot/css folder of the Blazor client project.
2. Import Bootstrap using something like Libman from unpkg so you get the source files as well.  (In Visual Studio this is under Add > Client Side Library when right clicking on the project)

<img width="367" alt="image" src="https://user-images.githubusercontent.com/4465616/192571878-beba6121-ff1d-4001-933f-434dfb0659b9.png">

3. Update the path in your bootstrap.scss file to be:

`@import "../lib/bootstrap/scss/bootstrap";`

4. Compile the file.  You can use the Web Compiler extension in Visual Studio.
5. Update the index.html file to point to the compiled css file.

`<link href="css/bootstrap.min.css" rel="stylesheet" />`

Everything is then wired up to use the light theme.  You will need to update the _light.scss and _dark.scss files to match any changes from Bootstrap 4 to Bootstrap 5.

https://getbootstrap.com/docs/5.0/migration/

**Comment by lonix1** [comment]
I looked everywhere for a blazor theme that looks like fluentui. You'd think that since blazor is a MS product, and many organisations adopted blazor, and probably use azure/office365/windows, that there'd be a fluentui/fast theme - but there isn't. 

This is the only repo I've found that helps in this matter... it's not perfect but it takes you most of the way there, thanks!

**Comment by scottkuhl** [comment]
> I looked everywhere for a blazor theme that looks like fluentui. You'd think that since blazor is a MS product, and many organisations adopted blazor, and probably use azure/office365/windows, that there'd be a fluentui/fast theme - but there isn't.

I agree.  I am really surprised we have not seen a Fluent native Blazor library from them.  Fast is just some fluent wrappers on JavaScript.

IMO, MS would be better off focusing on Blazor Native for desktop and mobile, port all their controls including the Windows Community Toolkit to Blazor and sunset Xamarin / Maui.  Blazor has so much momentum right now, and Maui and WinUI need so much work.

Hope this helps though in the meantime.

**Comment by lonix1** [comment]
Agreed. To add to that, the most amazing piece of tech I've seen recently is the [Mobile Blazor Bindings](https://github.com/dotnet/MobileBlazorBindings/) project. It's a pity they prioritised MAUI over that.
